### ISSUE TITLE
Unfortunately does not work

### ISSUE THREAD

**Issue by razordesign** [sebastianhaas/medical-appointment-scheduling-server#11]
It's no possible to install bunyan-syslog still, errors with it with node-gyp

**Comment by sebastianhaas** [comment]
Oh, sorry to hear that, but I have it running on Heroku [here](https://scheduling-server.herokuapp.com/), plus CI seems to pass [fine](https://travis-ci.org/sebastianhaas/medical-appointment-scheduling-server/branches).

I do had problems with bunyan-syslog on Windows though, any chance you're running a Windows machine? In that case there is already an open issue pending at [node-bunyan-syslog](https://github.com/mcavage/node-bunyan-syslog/issues/29).

It should be easy to get rid of the syslog stuff though, you could try to remove it from the `package.json` dependencies and remove lines 5 and 13-22 in `server.js`. I would love to hear if it works for you that way, so please let me know.

**Comment by sebastianhaas** [comment]
I just removed the syslog logging stream, please let me know if this doesn't solve your problems.
